################ English language ##################
# [en]
# languageName = "en"
# languageCode = "en-us"
# contentDir = "content/english"
# weight = 1

[cn]
languageName = "cn"
languageCode = "zh-cn"
contentDir = "content/chinese"
weight = 1
