############# English navigation ##############

# main menu
[[main]]
name = "主页"
url = "/"
weight = 1

[[main]]
name = "笔记"
url = "/blog"
weight = 2

[[main]]
name = "文档"
url = "/docs"
weight = 3

[[main]]
name = "按分类"
url = "/categories"
waight = 4

[[main]]
name = "按标签"
url = "/tags"
waight = 5

# [[main]]
# name = "About"
# url = "/about"
# weight = 2

# [[main]]
# name = "Elements"
# url = "/elements"
# weight = 3

# [[main]]
# weight = 4
# name = "Pages"

# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "/blog"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
# [[footer]]
# name = "About"
# url = "/about"
# weight = 1

# [[footer]]
# name = "Elements"
# url = "/elements"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 3

 [[footer]]
name = "HOME"
url = "/"
weight = 1

 [[footer]]
name = "BLOG"
url = "/blog"
weight = 2

 [[footer]]
name = "CATEGORIES"
url = "/categories"
waight = 3


